### ISSUE TITLE
FYI Admins

### ISSUE THREAD

**Issue by MtechnikX** [LetsCodeOnline/TwitchAPI#1]
I locked a couple of branches for time being to protect what we have and disabled force pushing, prevent branches from being deleted, and require status checks before merging. However, if you have the admin permission to unlock it for a reason, then you can, just be sure to relock it back afterwords if there are any complications. Again, do not leave it unlocked.

**Comment by SimulatedGREG** [comment]
What's the point of locking the branches ? We are the only ones that can push.

**Comment by MtechnikX** [comment]
Because we have a coupe of others who were interested in using this and i dont want it to mess ujp the main or backup branches

**Comment by SimulatedGREG** [comment]
Anybody can clone down the repo all they want, it's a public repo. But that doesn't mean they can push changes, they aren't a contributor to the repo. If they are wanting to do so, then they create a pull request that seeks permission to merge their changes. So there isn't a need to protect the branches. The protection you are thinking of is already part of the nature of how github functions.

**Comment by MtechnikX** [comment]
I keep forgetting that :8ball:

**Comment by AkiraLaine** [comment]
I'll close this then

**Comment by jackel27** [comment]
hmm. ok, just a few changes and good.
